### ISSUE TITLE
[Bug]ARが起動しないバグ

### ISSUE THREAD

**Issue by kunokuno** [kunokuno/SyuGo#9]
スマホの機種によってはARのカメラ機能がうまく動作せず、アプリが落ちる
アプリが落ちた機種
・paselowの友達の機種(なんだっけ？)

**Comment by kunokuno** [comment]
忘れてたので記述
発覚：第１回ユーザーテスト

**Comment by paselow-I** [comment]
SH02H
あくふぉん
Androidバージョンは6.0.1

明らかにカメラのせいなんだけど
エラーログ取れる状況じゃなかったのと，日常的に会える友人ではないので具体的な原因は不明

**Comment by kunokuno** [comment]
Androidバージョンが【6.0】以上だとカメラはダメみたいです...

**Comment by kunokuno** [comment]
Androidバージョン【6.0】のカメラに対応したのでclose
